### ISSUE TITLE
占位符数量触发扩容异常

### ISSUE THREAD

**Issue by Lynn-wu** [bukajsytlos/named-messageformat#1]
在主文件代码987行，formats是Map类型，无法使用System.arraycopy来复制。formats无需手动扩容，直接删除代码即可。
`if (offsetNumber >= offsets.length) {
      int newLength = offsets.length * 2;
      Format[] newFormats = new Format[newLength];
      int[] newOffsets = new int[newLength];
      String[] newArgumentNames = new String[newLength];
      System.arraycopy(formats, 0, newFormats, 0, maxOffset + 1);
      System.arraycopy(offsets, 0, newOffsets, 0, maxOffset + 1);
      System.arraycopy(argumentNames, 0, newArgumentNames, 0, maxOffset + 1);
      offsets = newOffsets;
      argumentNames = newArgumentNames;
    }`

**Comment by bukajsytlos** [comment]
thanks. should be fixed now
